### ISSUE TITLE
Commit to master not triggering Codepipeline Source Stage.

### ISSUE THREAD

**Issue by ecout** [aws-quickstart/quickstart-trek10-serverless-enterprise-cicd#15]
Hello,

There's nothing unusual about my set up. It simple won't trigger the automatic Code Pipeline Source stage.

I'm simply talking about the initial commit. I performed the commit manually as I have ssh keys for multiple accounts in other regions. Git client to AWS Code Commit works as expected.
Repro Steps:
Pre-Requisites:
I managed to make an initial test of the flow by using the Master Branch and then MANUALLY doing a Release Change. So the first thing is the initial commit didn't trigger automatic codepipeline execution. No ERRORS were given in the Service Account Stack.

Test Steps:

1. Create TWO branches in local repo with different code. 
2. Change the Description field in package.json
3 Add a logger.info entry to the lambda's code

Commit and push each branch to AWS Code Commit.

Expected result:
A Code Pipeline Stack is created for each branch and each branch is deployed independently as described by the Gitflow Workflow standard.

Actual: Each branch throws the following error. Like I said the initial test ran successfully using master. 
**User: arn:aws:sts::ACCT_ID:assumed-role/Service-Acct-AWS-QA-RE-30-DynamicPipelineMakerLamb-TGS9UKY3VJSV/Service-Acct-AWS-QA-RE-30-DynamicPipelineMakerLamb-1BPY72T25HD4E
 is not authorized to perform: codepipeline:CreatePipeline on resource: arn:aws:codepipeline:us-east-1:790138125387:Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-bra-Pipeline-F97LYZMZ2UWE (Service: AWSCodePipeline; Status Code: 400; Error Code: AccessDeniedException; Request ID: 2b62fb10-8ea2-4a88-a959-5119657db22b)

** 
It looks like the Child Stack is missing the Codepipeline permissions on the STS roles. 
As for the version of the CF templates I simply used the links posted in your PDF guide here:
https://aws-quickstart.s3.amazonaws.com/quickstart-trek10-serverless-enterprise-cicd/doc/serverless-cicd-for-the-enterprise-on-the-aws-cloud.pdf
[issue-15-Errors.zip](https://github.com/aws-quickstart/quickstart-trek10-serverless-enterprise-cicd/files/3511581/issue-15-Errors.zip)

Thanks for any help you can provide.

Edit:
Attached is zip file with the following contents:

- Service Acct Role's Policy: arn-aws-iam--Service_acct_ID-role/Service-Acct-AWS-QA-RE-30-DynamicPipelineMakerLamb-TGS9UKY3VJSV_policy.json 
- CF Stack Template where the error was shown: CFTemplateFailedStack.yaml

**Comment by ecout** [comment]
Update: I figured out the root cause. The problem is the IAM policy for this role does not match the ARN of the Codepipeline BECAUSE the inputs entered on the Service Account stack were too long and the CF code truncated the value of the arn.

See policy arn is:
arn:aws:codepipeline:us-east-1:790138125387:Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-branch-*

And Actual Codepipeline according to the error is:
arn:aws:codepipeline:us-east-1:790138125387:Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-bra-Pipeline-F97LYZMZ2UWE

So ...-branch-* won't match ...-bra-Pipeline-F97LYZMZ2UWE

Any chance you can add validation for Input length on your templates? The challenge is that each service has different behavior. Thanks!

**Comment by ecout** [comment]
Also here are the logs for the Dynamic Codepipeline Lambda Maker - Notice the error at the bottom as the lambda finds the Dynamic stack already exists but it is in Failed status because of the error above.

           
01:49:16
START RequestId: c55aa43c-ff3d-44af-8416-bfe0b2e4c308 Version: $LATEST

01:49:16
[INFO]	2019-08-17T01:49:16.447Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	event:{"Records": [{"awsRegion": "us-east-1", "codecommit": {"references": [{"commit": "90a0acec28a3b0c71a4dde15252222eadfffb02d", "created": true, "ref": "refs/heads/einar"}]}, "customData": "{\"SecretArnDev\": \"arn:aws:secretsmanager:us-east-1:790138125387:secret:sample-secret-us-east-1-790138125387-dev-JZOeLn\",\"SecretsManag

01:49:16
[INFO]	2019-08-17T01:49:16.447Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	reference:{"commit": "90a0acec28a3b0c71a4dde15252222eadfffb02d", "created": true, "ref": "refs/heads/einar"}

01:49:16
[INFO]	2019-08-17T01:49:16.447Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	created new branch:einar, creating pipeline for this branch

01:49:16
[INFO]	2019-08-17T01:49:16.457Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	creating stack: Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-branch-einar

01:50:17
Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: WaiterError Traceback (most recent call last): File "/var/task/index.py", line 82, in lambda_handler future.result() File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 425, in result return self.__get_result() File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_res

01:50:17
END RequestId: c55aa43c-ff3d-44af-8416-bfe0b2e4c308

01:50:17
REPORT RequestId: c55aa43c-ff3d-44af-8416-bfe0b2e4c308	Duration: 60991.36 ms	Billed Duration: 61000 ms Memory Size: 128 MB	Max Memory Used: 70 MB

01:50:40
START RequestId: 461b39c0-39ef-4c4c-a8e0-926fa4350379 Version: $LATEST

01:50:40
[INFO]	2019-08-17T01:50:40.992Z	461b39c0-39ef-4c4c-a8e0-926fa4350379	event:{"Records": [{"awsRegion": "us-east-1", "codecommit": {"references": [{"commit": "e2e06fad2f306bbe19cb4fe7315da99def18fe9c", "created": true, "ref": "refs/heads/other"}]}, "customData": "{\"SecretArnDev\": \"arn:aws:secretsmanager:us-east-1:790138125387:secret:sample-secret-us-east-1-790138125387-dev-JZOeLn\",\"SecretsManag

01:50:40
[INFO]	2019-08-17T01:50:40.992Z	461b39c0-39ef-4c4c-a8e0-926fa4350379	reference:{"commit": "e2e06fad2f306bbe19cb4fe7315da99def18fe9c", "created": true, "ref": "refs/heads/other"}

01:50:40
[INFO]	2019-08-17T01:50:40.992Z	461b39c0-39ef-4c4c-a8e0-926fa4350379	created new branch:other, creating pipeline for this branch

01:50:40
[INFO]	2019-08-17T01:50:40.997Z	461b39c0-39ef-4c4c-a8e0-926fa4350379	creating stack: Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-branch-other

01:50:41
An error occurred (AlreadyExistsException) when calling the CreateStack operation: Stack [Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-branch-other] already exists: AlreadyExistsException Traceback (most recent call last): File "/var/task/index.py", line 82, in lambda_handler future.result() File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 425,

01:50:41
END RequestId: 461b39c0-39ef-4c4c-a8e0-926fa4350379

01:50:41
REPORT RequestId: 461b39c0-39ef-4c4c-a8e0-926fa4350379	Duration: 227.94 ms	Billed Duration: 300 ms Memory Size: 128 MB	Max Memory Used: 70 MB

01:51:20
START RequestId: c55aa43c-ff3d-44af-8416-bfe0b2e4c308 Version: $LATEST

01:51:20
[INFO]	2019-08-17T01:51:20.631Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	event:{"Records": [{"awsRegion": "us-east-1", "codecommit": {"references": [{"commit": "90a0acec28a3b0c71a4dde15252222eadfffb02d", "created": true, "ref": "refs/heads/einar"}]}, "customData": "{\"SecretArnDev\": \"arn:aws:secretsmanager:us-east-1:790138125387:secret:sample-secret-us-east-1-790138125387-dev-JZOeLn\",\"SecretsManag

01:51:20
[INFO]	2019-08-17T01:51:20.631Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	reference:{"commit": "90a0acec28a3b0c71a4dde15252222eadfffb02d", "created": true, "ref": "refs/heads/einar"}

01:51:20
[INFO]	2019-08-17T01:51:20.631Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	created new branch:einar, creating pipeline for this branch

01:51:20
[INFO]	2019-08-17T01:51:20.637Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	creating stack: Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-branch-einar

01:51:20
An error occurred (AlreadyExistsException) when calling the CreateStack operation: Stack [Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-branch-einar] already exists: AlreadyExistsException Traceback (most recent call last): File "/var/task/index.py", line 82, in lambda_handler future.result() File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 425,

01:51:20
END RequestId: c55aa43c-ff3d-44af-8416-bfe0b2e4c308

01:51:20
REPORT RequestId: c55aa43c-ff3d-44af-8416-bfe0b2e4c308	Duration: 206.44 ms	Billed Duration: 300 ms Memory Size: 128 MB	Max Memory Used: 71 MB

01:52:30
START RequestId: 461b39c0-39ef-4c4c-a8e0-926fa4350379 Version: $LATEST

01:52:30
[INFO]	2019-08-17T01:52:30.439Z	461b39c0-39ef-4c4c-a8e0-926fa4350379	event:{"Records": [{"awsRegion": "us-east-1", "codecommit": {"references": [{"commit": "e2e06fad2f306bbe19cb4fe7315da99def18fe9c", "created": true, "ref": "refs/heads/other"}]}, "customData": "{\"SecretArnDev\": \"arn:aws:secretsmanager:us-east-1:790138125387:secret:sample-secret-us-east-1-790138125387-dev-JZOeLn\",\"SecretsManag

01:52:30
[INFO]	2019-08-17T01:52:30.439Z	461b39c0-39ef-4c4c-a8e0-926fa4350379	reference:{"commit": "e2e06fad2f306bbe19cb4fe7315da99def18fe9c", "created": true, "ref": "refs/heads/other"}

01:52:30
[INFO]	2019-08-17T01:52:30.439Z	461b39c0-39ef-4c4c-a8e0-926fa4350379	created new branch:other, creating pipeline for this branch

01:52:30
[INFO]	2019-08-17T01:52:30.457Z	461b39c0-39ef-4c4c-a8e0-926fa4350379	creating stack: Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-branch-other

01:52:30
An error occurred (AlreadyExistsException) when calling the CreateStack operation: Stack [Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-branch-other] already exists: AlreadyExistsException Traceback (most recent call last): File "/var/task/index.py", line 82, in lambda_handler future.result() File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 425,

01:52:30
END RequestId: 461b39c0-39ef-4c4c-a8e0-926fa4350379

01:52:30
REPORT RequestId: 461b39c0-39ef-4c4c-a8e0-926fa4350379	Duration: 197.99 ms	Billed Duration: 200 ms Memory Size: 128 MB	Max Memory Used: 71 MB

01:53:08
START RequestId: c55aa43c-ff3d-44af-8416-bfe0b2e4c308 Version: $LATEST

01:53:08
[INFO]	2019-08-17T01:53:08.990Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	event:{"Records": [{"awsRegion": "us-east-1", "codecommit": {"references": [{"commit": "90a0acec28a3b0c71a4dde15252222eadfffb02d", "created": true, "ref": "refs/heads/einar"}]}, "customData": "{\"SecretArnDev\": \"arn:aws:secretsmanager:us-east-1:790138125387:secret:sample-secret-us-east-1-790138125387-dev-JZOeLn\",\"SecretsManag

01:53:08
[INFO]	2019-08-17T01:53:08.990Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	reference:{"commit": "90a0acec28a3b0c71a4dde15252222eadfffb02d", "created": true, "ref": "refs/heads/einar"}

01:53:08
[INFO]	2019-08-17T01:53:08.990Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	created new branch:einar, creating pipeline for this branch

01:53:09
[INFO]	2019-08-17T01:53:08.997Z	c55aa43c-ff3d-44af-8416-bfe0b2e4c308	creating stack: Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-branch-einar

01:53:09
An error occurred (AlreadyExistsException) when calling the CreateStack operation: Stack [Service-Acct-AWS-QA-RE-3044-LambdaStack-PI4ML50JV46Q-ProjectPipelineStack-branch-einar] already exists: AlreadyExistsException Traceback (most recent call last): File "/var/task/index.py", line 82, in lambda_handler future.result() File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 425,

01:53:09
END RequestId: c55aa43c-ff3d-44af-8416-bfe0b2e4c308

**Comment by awarzon** [comment]
Thanks @ecout for finding this root cause. Submitted https://github.com/aws-quickstart/quickstart-trek10-serverless-enterprise-cicd/pull/22 to solve this

**Comment by ecout** [comment]
> Thanks @ecout for finding this root cause. Submitted #22 to solve this

YAY!!! Thanks!
